import { authOptions } from "@/lib/auth/options";
import { AuthSessionProvider } from "@/lib/providers/AuthSessionProvider";
import { ReduxProvider } from "@/lib/providers/ReduxProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const impact = localFont({
  variable: "--font-impact",
  src: "../../public/fonts/impact.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions); // pass session to AuthSessionProvider from the server so when we access useSession() to validate authination it wont flicker, since we pass it here
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${impact.variable} antialiased`}>
        <AuthSessionProvider session={session}>
          <ReduxProvider>
            {children}
            <SpeedInsights />
            {/*Speed Insights in Vercel to Validate Performance*/}
          </ReduxProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
