import { Header } from "@/components/layout/Header";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const impact = localFont({
  variable: "--font-impact",
  src: "../../public/fonts/impact.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${impact.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
